// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-7u8vRx5dc2t5GepfgeWESNIhopo6-_Y',
    appId: '1:24902260540:web:e28a401d5ded2617f2b039',
    messagingSenderId: '24902260540',
    projectId: 'jupging-login',
    authDomain: 'jupging-login.firebaseapp.com',
    storageBucket: 'jupging-login.appspot.com',
    measurementId: 'G-E9HPTQRDML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUJ2OZfML68BPR0Qd5n1Dpsm48TXaVwXU',
    appId: '1:24902260540:android:2013b370976b5dc1f2b039',
    messagingSenderId: '24902260540',
    projectId: 'jupging-login',
    storageBucket: 'jupging-login.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6ima8J7Ygov9W3Q4dvmCbKBWBi6XBeqM',
    appId: '1:24902260540:ios:93dc8fe39e176e90f2b039',
    messagingSenderId: '24902260540',
    projectId: 'jupging-login',
    storageBucket: 'jupging-login.appspot.com',
    iosClientId: '24902260540-h2h95ct20u88srqmigo1naebqimaaal9.apps.googleusercontent.com',
    iosBundleId: 'com.example.gdscProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6ima8J7Ygov9W3Q4dvmCbKBWBi6XBeqM',
    appId: '1:24902260540:ios:e819e7a6061af2bff2b039',
    messagingSenderId: '24902260540',
    projectId: 'jupging-login',
    storageBucket: 'jupging-login.appspot.com',
    iosClientId: '24902260540-ask7j47o07scdqr39lhnmqvq1lluejjo.apps.googleusercontent.com',
    iosBundleId: 'com.example.gdscProject.RunnerTests',
  );
}
